# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: booking.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rbooking.proto\";\n\x0b\x42ookingInfo\x12\x0e\n\x06userid\x18\x01 \x01(\t\x12\x1c\n\x05\x64\x61tes\x18\x02 \x03(\x0b\x32\r.ShowtimeSlot\",\n\x0cShowtimeSlot\x12\x0c\n\x04\x64\x61te\x18\x01 \x01(\t\x12\x0e\n\x06movies\x18\x02 \x03(\t\"\x18\n\x06UsedID\x12\x0e\n\x06userid\x18\x01 \x01(\t\"<\n\x0bUserBooking\x12\x0e\n\x06userid\x18\x01 \x01(\t\x12\x0c\n\x04\x64\x61te\x18\x02 \x01(\t\x12\x0f\n\x07movieid\x18\x03 \x01(\t\"\r\n\x0b\x45mptyObject2\x94\x01\n\x07\x42ooking\x12-\n\x0bGetBookings\x12\x0c.EmptyObject\x1a\x0c.BookingInfo\"\x00\x30\x01\x12.\n\x13GetBookingsByUserID\x12\x07.UsedID\x1a\x0c.BookingInfo\"\x00\x12*\n\nAddBooking\x12\x0c.UserBooking\x1a\x0c.BookingInfo\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'booking_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_BOOKINGINFO']._serialized_start=17
  _globals['_BOOKINGINFO']._serialized_end=76
  _globals['_SHOWTIMESLOT']._serialized_start=78
  _globals['_SHOWTIMESLOT']._serialized_end=122
  _globals['_USEDID']._serialized_start=124
  _globals['_USEDID']._serialized_end=148
  _globals['_USERBOOKING']._serialized_start=150
  _globals['_USERBOOKING']._serialized_end=210
  _globals['_EMPTYOBJECT']._serialized_start=212
  _globals['_EMPTYOBJECT']._serialized_end=225
  _globals['_BOOKING']._serialized_start=228
  _globals['_BOOKING']._serialized_end=376
# @@protoc_insertion_point(module_scope)
